name: Build RPM pakcage

on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Architecture to build rpm, one of amd64,arm64v8,ppc64le'
        default: 'amd64'
        required: true
      item:
        description: 'Package to build rpm, one of binutils,gcc,gdb'
        default: 'binutils'
        required: true

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Build rpm
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker run --rm -v$(pwd):/root/build_rpm ${{ github.event.inputs.arch }}/centos:7 bash /root/build_rpm/build_rpm.sh ${{ github.event.inputs.item }}
        
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        releaseId: ${{ github.event.inputs.item }}
        args: 'RPMS/*.rpm'
